base_model: alpindale/Mistral-7B-v0.2-hf
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer

load_in_8bit: false
load_in_4bit: false
strict: false

rl: orpo
orpo_alpha: 0.1
remove_unused_columns: false
chat_template: chatml
datasets:
  - data_files: /mnt/nas/seongyun/MPA/data/training/preferences_v1_responses_single_dim_no_sys_for_orpo_64k_v2.jsonl
    type: orpo.chat_template
    # conversation: mistral
      
dataset_prepared_path:
hub_model_id: kaist-ai/mpa-Mistral-7b-v0.2-hf-no-sys-sft-66k-orpo
# hub_strategy: checkpoint
# val_set_size: 0
output_dir: /mnt/nas/suehyun/axolotl/outputs/mpa-Mistral-7b-v0.2-hf-no-sys-sft-66k-orpo

sequence_len: 4096
sample_packing: false
pad_to_sequence_len: true
eval_sample_packing: false

wandb_project: mpa
wandb_entity: seongyun
wandb_watch:
wandb_name: mpa_mistral-7b-v0.2-hf-no-sys-66k-orpo
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 1
num_epochs: 2
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.000005

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
# evals_per_epoch: 4
eval_table_size:
# eval_max_new_tokens: 128
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
